// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: school-manager-auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SchoolManagerAuthServiceClient is the client API for SchoolManagerAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchoolManagerAuthServiceClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
}

type schoolManagerAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchoolManagerAuthServiceClient(cc grpc.ClientConnInterface) SchoolManagerAuthServiceClient {
	return &schoolManagerAuthServiceClient{cc}
}

func (c *schoolManagerAuthServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/proto.SchoolManagerAuthService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchoolManagerAuthServiceServer is the server API for SchoolManagerAuthService service.
// All implementations must embed UnimplementedSchoolManagerAuthServiceServer
// for forward compatibility
type SchoolManagerAuthServiceServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	mustEmbedUnimplementedSchoolManagerAuthServiceServer()
}

// UnimplementedSchoolManagerAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSchoolManagerAuthServiceServer struct {
}

func (UnimplementedSchoolManagerAuthServiceServer) SignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedSchoolManagerAuthServiceServer) mustEmbedUnimplementedSchoolManagerAuthServiceServer() {
}

// UnsafeSchoolManagerAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchoolManagerAuthServiceServer will
// result in compilation errors.
type UnsafeSchoolManagerAuthServiceServer interface {
	mustEmbedUnimplementedSchoolManagerAuthServiceServer()
}

func RegisterSchoolManagerAuthServiceServer(s grpc.ServiceRegistrar, srv SchoolManagerAuthServiceServer) {
	s.RegisterService(&SchoolManagerAuthService_ServiceDesc, srv)
}

func _SchoolManagerAuthService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolManagerAuthServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SchoolManagerAuthService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolManagerAuthServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchoolManagerAuthService_ServiceDesc is the grpc.ServiceDesc for SchoolManagerAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchoolManagerAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SchoolManagerAuthService",
	HandlerType: (*SchoolManagerAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _SchoolManagerAuthService_SignIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "school-manager-auth.proto",
}
